Repository Volgarenok/spbspu-labs-2025-aads-a, pull requests merged in 2025-02, with the labels that each got.

#2 kushekbaev.danil/S0
  kushekbaev.danil/S0/credentials.cpp
  kushekbaev.danil/S0/credentials.hpp
  kushekbaev.danil/S0/main.cpp
  kushekbaev.danil/S0/test-credentials.cpp
  kushekbaev.danil/S0/test-main.cpp
Labels: fine

#3 savintsev.ilya/S0
  savintsev.ilya/S0/credentials.cpp
  savintsev.ilya/S0/credentials.hpp
  savintsev.ilya/S0/main.cpp
  savintsev.ilya/S0/test-credentials.cpp
  savintsev.ilya/S0/test-default.cpp
Labels: fine

#4 maslov.aleksey/S0
  maslov.aleksey/S0/credentials.cpp
  maslov.aleksey/S0/credentials.hpp
  maslov.aleksey/S0/main.cpp
  maslov.aleksey/S0/test-credentials.cpp
  maslov.aleksey/S0/test-main.cpp
Labels: fine

#14 abramov.vladislav/S0
  abramov.vladislav/S0/credentials.cpp
  abramov.vladislav/S0/credentials.hpp
  abramov.vladislav/S0/main.cpp
  abramov.vladislav/S0/test-credentials.cpp
  abramov.vladislav/S0/test-main.cpp
Labels: fine, gr 4

#11 maslevtsov.stanislav/S0
  maslevtsov.stanislav/S0/credentials.cpp
  maslevtsov.stanislav/S0/credentials.hpp
  maslevtsov.stanislav/S0/main.cpp
  maslevtsov.stanislav/S0/test-credentials.cpp
  maslevtsov.stanislav/S0/test-main.cpp
Labels: fine, gr 4

#10 dribas.sergey/S0
  dribas.sergey/S0/credentials.cpp
  dribas.sergey/S0/credentials.hpp
  dribas.sergey/S0/main.cpp
  dribas.sergey/S0/test-credentials.cpp
  dribas.sergey/S0/test-main.cpp
Labels: fine, gr 5

#8 aleksandrov.igor/S0
  aleksandrov.igor/S0/credentials.cpp
  aleksandrov.igor/S0/credentials.h
  aleksandrov.igor/S0/main.cpp
  aleksandrov.igor/S0/test-credentials.cpp
  aleksandrov.igor/S0/test-main.cpp
Labels: fine, gr 4

#7 hismatova.elizaveta/S0
  hismatova.elizaveta/S0/credentials.cpp
  hismatova.elizaveta/S0/credentials.hpp
  hismatova.elizaveta/S0/main.cpp
  hismatova.elizaveta/S0/test-credentials.cpp
  hismatova.elizaveta/S0/test-main.cpp
Labels: fine, gr 1

#6 alymova.ksenia/S0
  alymova.ksenia/S0/credentials.cpp
  alymova.ksenia/S0/credentials.hpp
  alymova.ksenia/S0/main.cpp
  alymova.ksenia/S0/test-credentials.cpp
  alymova.ksenia/S0/test-main.cpp
Labels: fine, gr 4

#5 demehin.maxim/S0
  demehin.maxim/S0/credentials.cpp
  demehin.maxim/S0/credentials.hpp
  demehin.maxim/S0/main.cpp
  demehin.maxim/S0/test-credentials.cpp
  demehin.maxim/S0/test-main.cpp
Labels: fine, gr 5

#13 averenkov.eugene/S0
  averenkov.eugene/S0/credentials.cpp
  averenkov.eugene/S0/credentials.hpp
  averenkov.eugene/S0/main.cpp
  averenkov.eugene/S0/test-credentials.cpp
  averenkov.eugene/S0/test-main.cpp
Labels: fine, gr 5

#15 cherkasov.nikita/S0
  cherkasov.nikita/S0/credentials.cpp
  cherkasov.nikita/S0/credentials.hpp
  cherkasov.nikita/S0/main.cpp
  cherkasov.nikita/S0/test-credentials.cpp
  cherkasov.nikita/S0/test-main.cpp
Labels: fine, gr 4

#16 mozhegova.maria/S0
  mozhegova.maria/S0/credentials.cpp
  mozhegova.maria/S0/credentials.hpp
  mozhegova.maria/S0/main.cpp
  mozhegova.maria/S0/test-credentials.cpp
  mozhegova.maria/S0/test-main.cpp
Labels: fine, gr 1

#12 petrov.nikita/S0
  petrov.nikita/S0/credentials.cpp
  petrov.nikita/S0/credentials.hpp
  petrov.nikita/S0/main.cpp
  petrov.nikita/S0/test-credentials.cpp
  petrov.nikita/S0/test-main.cpp
Labels: fine, gr 1

#18 tkach.danil/S0
  tkach.danil/S0/credentials.cpp
  tkach.danil/S0/credentials.hpp
  tkach.danil/S0/main.cpp
  tkach.danil/S0/test-credentials.cpp
  tkach.danil/S0/test-main.cpp
Labels: gr 1

#19 finaev.alexey/S0
  finaev.alexey/S0/credentials.cpp
  finaev.alexey/S0/credentials.hpp
  finaev.alexey/S0/main.cpp
  finaev.alexey/S0/test-credentials.cpp
  finaev.alexey/S0/test-main.cpp
Labels: gr 1

#20 kiselev.sergey/S0
  kiselev.sergey/S0/credentials.cpp
  kiselev.sergey/S0/credentials.hpp
  kiselev.sergey/S0/main.cpp
  kiselev.sergey/S0/test-credentials.cpp
  kiselev.sergey/S0/test-main.cpp
Labels: gr 5

#17 krylov.matvey/S0
  krylov.matvey/S0/credentials.cpp
  krylov.matvey/S0/credentials.hpp
  krylov.matvey/S0/main.cpp
  krylov.matvey/S0/test-credentials.cpp
  krylov.matvey/S0/test-main.cpp
Labels: gr 4

#22 kizhin.evgeniy/S0
  kizhin.evgeniy/S0/main.cpp
  kizhin.evgeniy/S0/out-name.cpp
  kizhin.evgeniy/S0/out-name.hpp
  kizhin.evgeniy/S0/test-module-S0.cpp
  kizhin.evgeniy/S0/test-out-name.cpp
Labels: fine, gr 5

#21 maslovskiy.vladislav/S0
  maslovskiy.vladislav/S0/credentials.cpp
  maslovskiy.vladislav/S0/credentials.hpp
  maslovskiy.vladislav/S0/main.cpp
  maslovskiy.vladislav/S0/test-credentials.cpp
  maslovskiy.vladislav/S0/test-main.cpp
Labels: fine, gr 4

#23 bocharov.egor/S0
  bocharov.egor/S0/credentials.cpp
  bocharov.egor/S0/credentials.hpp
  bocharov.egor/S0/main.cpp
  bocharov.egor/S0/test-credentials.cpp
  bocharov.egor/S0/test-main.cpp
Labels: fine, gr 5

#24 rychkov.mihail/S0
  rychkov.mihail/S0/credentials.cpp
  rychkov.mihail/S0/credentials.hpp
  rychkov.mihail/S0/main.cpp
  rychkov.mihail/S0/test-S0-unit.cpp
  rychkov.mihail/S0/test-credentials.cpp
Labels: fine, gr 1

#25 sveshnikov.michail/S0
  sveshnikov.michail/S0/credentials.cpp
  sveshnikov.michail/S0/credentials.hpp
  sveshnikov.michail/S0/main.cpp
  sveshnikov.michail/S0/test-credentials.cpp
  sveshnikov.michail/S0/test-main.cpp
Labels: fine, gr 4

#26 nikonov.andrew/S0
  nikonov.andrew/S0/credentials.cpp
  nikonov.andrew/S0/credentials.hpp
  nikonov.andrew/S0/main.cpp
  nikonov.andrew/S0/test-credentials.cpp
  nikonov.andrew/S0/test-main.cpp
Labels: fine, gr 4

#27 Brevnov.nikita/s0
  brevnov.nikita/S0/credentials.cpp
  brevnov.nikita/S0/credentials.hpp
  brevnov.nikita/S0/main.cpp
  brevnov.nikita/S0/test-credentials.cpp
  brevnov.nikita/S0/test-main.cpp
Labels: fine, gr 5

#28 lanovenko.ivan/S0
  lanovenko.ivan/S0/credentials.cpp
  lanovenko.ivan/S0/credentials.hpp
  lanovenko.ivan/S0/main.cpp
  lanovenko.ivan/S0/test-credentials.cpp
  lanovenko.ivan/S0/test-main.cpp
Labels: fine, gr 1

#29 gavrilova.polina/S0
  gavrilova.polina/S0/credentials.cpp
  gavrilova.polina/S0/credentials.hpp
  gavrilova.polina/S0/main.cpp
  gavrilova.polina/S0/test-credentials.cpp
  gavrilova.polina/S0/test-main.cpp
Labels: fine, gr 5

#31 karnauhova.alexandra/S0
  karnauhova.alexandra/S0/credentials.cpp
  karnauhova.alexandra/S0/credentials.hpp
  karnauhova.alexandra/S0/main.cpp
  karnauhova.alexandra/S0/test-credentials.cpp
  karnauhova.alexandra/S0/test-main.cpp
Labels: fine, gr 5

#32 belobrov.timofey/S0
  belobrov.timofey/S0/credentials.cpp
  belobrov.timofey/S0/credentials.hpp
  belobrov.timofey/S0/main.cpp
  belobrov.timofey/S0/test-credentials.cpp
  belobrov.timofey/S0/test-main.cpp
Labels: fine, gr 4

#33 asafov.andrew/S0
  asafov.andrew/S0/credentials.cpp
  asafov.andrew/S0/credentials.h
  asafov.andrew/S0/main.cpp
  asafov.andrew/S0/test-credentials.cpp
  asafov.andrew/S0/test-main.cpp
Labels: fine, gr 4

#34 evstyunichev.konstantin/S0
  evstyunichev.konstantin/S0/credentials.cpp
  evstyunichev.konstantin/S0/credentials.hpp
  evstyunichev.konstantin/S0/main.cpp
  evstyunichev.konstantin/S0/test-S0.main.cpp
  evstyunichev.konstantin/S0/test-credentials.cpp
Labels: fine, gr 5

#36 zholobov.oleg/S0
  zholobov.oleg/S0/credentials.cpp
  zholobov.oleg/S0/credentials.hpp
  zholobov.oleg/S0/main.cpp
  zholobov.oleg/S0/test-credentials.cpp
  zholobov.oleg/S0/test-main.cpp
Labels: fine, gr 5

#37 guseynov.guseyn/S0
  guseynov.guseyn/S0/credentials.cpp
  guseynov.guseyn/S0/credentials.hpp
  guseynov.guseyn/S0/main.cpp
  guseynov.guseyn/S0/test-credentials.cpp
  guseynov.guseyn/S0/test-main.cpp
Labels: fine, gr 1

#30 shramko.maksim/S0
  shramko.maksim/S0/credentials.cpp
  shramko.maksim/S0/credentials.hpp
  shramko.maksim/S0/main.cpp
  shramko.maksim/S0/test-credentials.cpp
  shramko.maksim/S0/test-main.cpp
Labels: fine, gr 1

#38 zakirov.marat/S0
  zakirov.marat/S0/main.cpp
  zakirov.marat/S0/personal_data.cpp
  zakirov.marat/S0/personal_data.hpp
  zakirov.marat/S0/test-main.cpp
  zakirov.marat/S0/test-personal_data.cpp
Labels: fine, gr 4

#39 smirnov.alexandr/S0
  smirnov.alexandr/S0/credentials.cpp
  smirnov.alexandr/S0/credentials.hpp
  smirnov.alexandr/S0/main.cpp
  smirnov.alexandr/S0/test-credentials.cpp
  smirnov.alexandr/S0/test-main.cpp
Labels: fine, gr 1

#40 sharifullina.sofia/S0
  sharifullina.sofia/S0/credentials.cpp
  sharifullina.sofia/S0/credentials.hpp
  sharifullina.sofia/S0/main.cpp
  sharifullina.sofia/S0/test-credentials.cpp
  sharifullina.sofia/S0/test-main.cpp
Labels: fine, gr 1

#41 komarova.anastasia/S0
  komarova.anastasia/S0/credentials.cpp
  komarova.anastasia/S0/credentials.hpp
  komarova.anastasia/S0/main.cpp
  komarova.anastasia/S0/test-credentials.cpp
  komarova.anastasia/S0/test-main.cpp
Labels: fine, gr 4

#42 Balashov.dima/S0
  balashov.dima/S0/credentials.cpp
  balashov.dima/S0/credentials.hpp
  balashov.dima/S0/main.cpp
  balashov.dima/S0/test-credentials.cpp
  balashov.dima/S0/test-main.cpp
Labels: fine, gr 1

#43 lebedev.alexandr/S0
  lebedev.alexandr/S0/credentials.cpp
  lebedev.alexandr/S0/credentials.hpp
  lebedev.alexandr/S0/main.cpp
  lebedev.alexandr/S0/test-credentials.cpp
  lebedev.alexandr/S0/test-main.cpp
Labels: fine, gr 1

#44 dirti.aldyn/S0
  dirti.aldyn/S0/credentials.cpp
  dirti.aldyn/S0/credentials.hpp
  dirti.aldyn/S0/main.cpp
  dirti.aldyn/S0/test-credentials.cpp
  dirti.aldyn/S0/test-main.cpp
Labels: fine, gr 5
