Repository Volgarenok/spbspu-labs-2025-aads-a, pull requests merged in 2025-05, with the labels that each got.

#57 tkach.danil/S1
  tkach.danil/S1/list.hpp
  tkach.danil/S1/list_const_iterator.hpp
  tkach.danil/S1/list_iterator.hpp
  tkach.danil/S1/main.cpp
  tkach.danil/S1/node.hpp
  tkach.danil/S1/test-list.cpp
  tkach.danil/S1/test-main.cpp
Labels: fine, gr 1, 7/9

#59 averenkov.eugene/S1
  averenkov.eugene/S1/constiterator.hpp
  averenkov.eugene/S1/iterator.hpp
  averenkov.eugene/S1/list.hpp
  averenkov.eugene/S1/main.cpp
  averenkov.eugene/S1/node.hpp
  averenkov.eugene/S1/test-list.cpp
  averenkov.eugene/S1/test-main.cpp
Labels: fine, gr 5, 6/9

#80 Bocharov.egor/S1
  bocharov.egor/S1/actions.cpp
  bocharov.egor/S1/actions.hpp
  bocharov.egor/S1/iterator.hpp
  bocharov.egor/S1/list.hpp
  bocharov.egor/S1/main.cpp
  bocharov.egor/S1/node.hpp
  bocharov.egor/S1/test-list.cpp
  bocharov.egor/S1/test-main.cpp
Labels: fine, gr 5, comedy artist, 7/9

#94 kizhin.evgeniy/S2
  kizhin.evgeniy/S2/io-utils.cpp
  kizhin.evgeniy/S2/io-utils.hpp
  kizhin.evgeniy/S2/main.cpp
  kizhin.evgeniy/S2/operations.cpp
  kizhin.evgeniy/S2/operations.hpp
  kizhin.evgeniy/S2/postfix-expression.cpp
  kizhin.evgeniy/S2/postfix-expression.hpp
  kizhin.evgeniy/S2/test-buffer.cpp
  kizhin.evgeniy/S2/test-module-S2.cpp
  kizhin.evgeniy/S2/test-utils.cpp
  kizhin.evgeniy/S2/test-utils.hpp
  kizhin.evgeniy/S2/token.cpp
  kizhin.evgeniy/S2/token.hpp
  kizhin.evgeniy/common/algorithm-utils.hpp
  kizhin.evgeniy/common/buffer.hpp
  kizhin.evgeniy/common/enable-if-input-iterator.hpp
  kizhin.evgeniy/common/forward-list-comparison.hpp
  kizhin.evgeniy/common/forward-list.hpp
  kizhin.evgeniy/common/queue.hpp
  kizhin.evgeniy/common/stack.hpp
  kizhin.evgeniy/common/type-utils.hpp
Labels: gr 5, 9/9

#83 kiselev.sergey/S2
  kiselev.sergey/S2/actionsExpr.cpp
  kiselev.sergey/S2/actionsExpr.hpp
  kiselev.sergey/S2/main.cpp
  kiselev.sergey/S2/test-dynamicArr.cpp
  kiselev.sergey/S2/test-main.cpp
  kiselev.sergey/S2/test-queue.cpp
  kiselev.sergey/S2/test-stack.cpp
  kiselev.sergey/common/dynamicArr.hpp
  kiselev.sergey/common/queue.hpp
  kiselev.sergey/common/stack.hpp
Labels: fine, gr 5, 7/9

#82 demehin.maxim/S2
  demehin.maxim/S1/main.cpp
  demehin.maxim/S2/exprs_manip.cpp
  demehin.maxim/S2/exprs_manip.hpp
  demehin.maxim/S2/main.cpp
  demehin.maxim/S2/test-main.cpp
  demehin.maxim/S2/test-queue-stack.cpp
  demehin.maxim/common/calc_utils.hpp
  demehin.maxim/common/data_utils.hpp
  demehin.maxim/common/dynamic_array.hpp
  demehin.maxim/common/dynamic_array_iterator.hpp
  demehin.maxim/common/list/list.hpp
  demehin.maxim/common/queue.hpp
  demehin.maxim/common/stack.hpp
Labels: fine, gr 5, 7/9

#88 maslevtsov.stanislav/S2
  maslevtsov.stanislav/S2/checked_operations.cpp
  maslevtsov.stanislav/S2/checked_operations.hpp
  maslevtsov.stanislav/S2/expression_processing.cpp
  maslevtsov.stanislav/S2/expression_processing.hpp
  maslevtsov.stanislav/S2/io_stack.cpp
  maslevtsov.stanislav/S2/io_stack.hpp
  maslevtsov.stanislav/S2/main.cpp
  maslevtsov.stanislav/S2/postfix_token.cpp
  maslevtsov.stanislav/S2/postfix_token.hpp
  maslevtsov.stanislav/S2/queue.hpp
  maslevtsov.stanislav/S2/queue_stack_base.hpp
  maslevtsov.stanislav/S2/stack.hpp
  maslevtsov.stanislav/S2/test-S2.cpp
  maslevtsov.stanislav/S2/test-postfix_token.cpp
  maslevtsov.stanislav/S2/test-queue.cpp
  maslevtsov.stanislav/S2/test-stack.cpp
Labels: fine, gr 4, 8/9

#106 alymova.ksenia/S2
  alymova.ksenia/S2/array.hpp
  alymova.ksenia/S2/main.cpp
  alymova.ksenia/S2/postfix.cpp
  alymova.ksenia/S2/postfix.hpp
  alymova.ksenia/S2/postfixProcess.cpp
  alymova.ksenia/S2/postfixProcess.hpp
  alymova.ksenia/S2/queue.hpp
  alymova.ksenia/S2/stack.hpp
  alymova.ksenia/S2/test-array.cpp
  alymova.ksenia/S2/test-main.cpp
  alymova.ksenia/S2/test-postfix-operators.cpp
Labels: fine, gr 4, 8/9

#75 petrov.nikita/S1
  petrov.nikita/S1/forward_ring_list.hpp
  petrov.nikita/S1/main.cpp
  petrov.nikita/S1/test-forward_ring_list.cpp
  petrov.nikita/S1/test-main.cpp
Labels: fine, gr 1, 5/9

#64 kushekbaev.danil/S1
  kushekbaev.danil/S1/constiterator.hpp
  kushekbaev.danil/S1/fwdlist.hpp
  kushekbaev.danil/S1/iterator.hpp
  kushekbaev.danil/S1/main.cpp
  kushekbaev.danil/S1/node.hpp
  kushekbaev.danil/S1/test-fwdlist.cpp
  kushekbaev.danil/S1/test-main.cpp
Labels: fine, gr 4, 8/9

#69 zholobov.oleg/S1
  zholobov.oleg/S1/CircularFwdList.hpp
  zholobov.oleg/S1/CircularFwdListIterators.hpp
  zholobov.oleg/S1/FwdListNode.hpp
  zholobov.oleg/S1/main.cpp
  zholobov.oleg/S1/test-list.cpp
  zholobov.oleg/S1/test-main.cpp
Labels: fine, gr 5, 7/9

#85 rychkov.mihail/S2
  rychkov.mihail/S2/bad_variant_access.cpp
  rychkov.mihail/S2/main.cpp
  rychkov.mihail/S2/queue.hpp
  rychkov.mihail/S2/queue_base.hpp
  rychkov.mihail/S2/safe_math.hpp
  rychkov.mihail/S2/stack.hpp
  rychkov.mihail/S2/test-S2-unit.cpp
  rychkov.mihail/S2/test-queue.cpp
  rychkov.mihail/S2/test-stack.cpp
  rychkov.mihail/S2/test-variant.cpp
  rychkov.mihail/S2/variant.hpp
  rychkov.mihail/S2/variant/base/copy_move_assign_base.hpp
  rychkov.mihail/S2/variant/base/copy_move_construct_base.hpp
  rychkov.mihail/S2/variant/base/getters.hpp
  rychkov.mihail/S2/variant/base/route_visit.hpp
  rychkov.mihail/S2/variant/base/union_base.hpp
  rychkov.mihail/S2/variant/base/visitor_helpers.hpp
  rychkov.mihail/S2/variant/bases.hpp
  rychkov.mihail/S2/variant/class/access.hpp
  rychkov.mihail/S2/variant/class/construct_destruct.hpp
  rychkov.mihail/S2/variant/class/visit.hpp
  rychkov.mihail/S2/variant/declaration.hpp
  rychkov.mihail/S2/variant/tools.hpp
  rychkov.mihail/S2/variant/traits.hpp
  rychkov.mihail/common/functional.hpp
  rychkov.mihail/common/mem_checker.hpp
  rychkov.mihail/common/type_tools.hpp
  rychkov.mihail/common/type_traits.hpp
Labels: fine, gr 1, 9/9

#121 alymova.ksenia/S4
  alymova.ksenia/S4/main.cpp
  alymova.ksenia/S4/test-main.cpp
  alymova.ksenia/S4/test-tree.cpp
  alymova.ksenia/S4/tree-2-3.hpp
  alymova.ksenia/S4/tree-const-iterator-impl.hpp
  alymova.ksenia/S4/tree-iterator-impl.hpp
  alymova.ksenia/S4/tree-iterators.hpp
  alymova.ksenia/S4/tree-node.hpp
  alymova.ksenia/S4/utils.cpp
  alymova.ksenia/S4/utils.hpp
Labels: fine, gr 4, 9/9

#111 demehin.maxim/S4
  demehin.maxim/S4/main.cpp
  demehin.maxim/S4/test-main.cpp
  demehin.maxim/S4/test-tree.cpp
  demehin.maxim/S4/tree_manips.cpp
  demehin.maxim/S4/tree_manips.hpp
  demehin.maxim/common/tree/cIterator.hpp
  demehin.maxim/common/tree/iterator.hpp
  demehin.maxim/common/tree/node.hpp
  demehin.maxim/common/tree/tree.hpp
Labels: gr 5, 7/9

#87 tkach.danil/S2
  tkach.danil/S2/dynamic_array.hpp
  tkach.danil/S2/main.cpp
  tkach.danil/S2/print.hpp
  tkach.danil/S2/queue.hpp
  tkach.danil/S2/stack.hpp
  tkach.danil/S2/test-main.cpp
  tkach.danil/S2/test-queue.cpp
  tkach.danil/S2/test-stack.cpp
Labels: fine, gr 1, 7/9

#62 aleksandrov.igor/S1
  aleksandrov.igor/S1/const-iterator.hpp
  aleksandrov.igor/S1/iterator.hpp
  aleksandrov.igor/S1/list-utils.cpp
  aleksandrov.igor/S1/list-utils.hpp
  aleksandrov.igor/S1/list.hpp
  aleksandrov.igor/S1/main.cpp
  aleksandrov.igor/S1/node.hpp
  aleksandrov.igor/S1/test-list.cpp
  aleksandrov.igor/S1/test-main.cpp
Labels: fine, gr 4, 8/9, 9/9

#97 maslov.aleksey/S2
  maslov.aleksey/S2/calculatorExpression.cpp
  maslov.aleksey/S2/calculatorExpression.hpp
  maslov.aleksey/S2/main.cpp
  maslov.aleksey/S2/test-main.cpp
  maslov.aleksey/S2/test-queue.cpp
  maslov.aleksey/S2/test-stack.cpp
  maslov.aleksey/common/queue.hpp
  maslov.aleksey/common/stack.hpp
Labels: fine, gr 1, 7/9
