Repository Volgarenok/spbspu-labs-2025-aads-a, pull requests merged in 2025-09, with the labels that each got.

#98 smirnov.alexandr/S2
  smirnov.alexandr/S2/conversion.cpp
  smirnov.alexandr/S2/conversion.hpp
  smirnov.alexandr/S2/main.cpp
  smirnov.alexandr/S2/read_expressions.cpp
  smirnov.alexandr/S2/read_expressions.hpp
  smirnov.alexandr/S2/test-main.cpp
  smirnov.alexandr/S2/test-queue.cpp
  smirnov.alexandr/S2/test-stack.cpp
  smirnov.alexandr/S2/utils.cpp
  smirnov.alexandr/S2/utils.hpp
  smirnov.alexandr/common/utils/queue.hpp
  smirnov.alexandr/common/utils/stack.hpp
Labels: fine, gr 1, 4/9

#72 krylov.matvey/S1
  krylov.matvey/S1/list-constiterators.hpp
  krylov.matvey/S1/list-iterators.hpp
  krylov.matvey/S1/list-node.hpp
  krylov.matvey/S1/list.hpp
  krylov.matvey/S1/main.cpp
  krylov.matvey/S1/test-list.cpp
  krylov.matvey/S1/test-main.cpp
Labels: gr 4, 6/9

#220 shabalin.dmitrii/S0
  shabalin.dmitrii/credentials.cpp
  shabalin.dmitrii/credentials.hpp
  shabalin.dmitrii/main.cpp
  shabalin.dmitrii/test-credentials.cpp
  shabalin.dmitrii/test-main.cpp
Labels: gr 5

#73 sveshnikov.michail/S1
  sveshnikov.michail/S1/fwd-citerator.hpp
  sveshnikov.michail/S1/fwd-iterator.hpp
  sveshnikov.michail/S1/fwdlist-node.hpp
  sveshnikov.michail/S1/fwdlist-ring.hpp
  sveshnikov.michail/S1/io-sequences.cpp
  sveshnikov.michail/S1/io-sequences.hpp
  sveshnikov.michail/S1/main.cpp
  sveshnikov.michail/S1/test-fwdlist.cpp
  sveshnikov.michail/S1/test-main.cpp
Labels: fine, gr 4, 7/9, urlagushka

#175 shramko.maksim/S2
  shramko.maksim/S1/functionsForList.hpp
  shramko.maksim/S2/main.cpp
  shramko.maksim/S2/print.hpp
  shramko.maksim/S2/queue.cpp
  shramko.maksim/S2/queue.hpp
  shramko.maksim/S2/stack.cpp
  shramko.maksim/S2/stack.hpp
  shramko.maksim/S2/test-main.cpp
  shramko.maksim/S2/test-queue.cpp
  shramko.maksim/S2/test-stack.cpp
  shramko.maksim/common/FwdList.hpp
  shramko.maksim/common/FwdListNode.hpp
  shramko.maksim/common/constIterator.hpp
  shramko.maksim/common/iterator.hpp
Labels: gr 1, 3/9

#116 averenkov.eugene/S4
  averenkov.eugene/S4/main.cpp
  averenkov.eugene/S4/test-main.cpp
  averenkov.eugene/S4/test-tree.cpp
  averenkov.eugene/common/BiTree.hpp
  averenkov.eugene/common/constIterator.hpp
  averenkov.eugene/common/iterator.hpp
  averenkov.eugene/common/node.hpp
Labels: gr 5, 6/9
