Repository Volgarenok/spbspu-labs-2025-aads-a, pull requests merged in 2025-03, with the labels that each got.

#1 dobsov.sergey/S0
  dobsov.sergey/S0/credentials.cpp
  dobsov.sergey/S0/credentials.hpp
  dobsov.sergey/S0/main.cpp
  dobsov.sergey/S0/test-credentials.cpp
  dobsov.sergey/S0/test-main.cpp
Labels: fine

#68 rychkov.mihail/S1
  rychkov.mihail/S1/list.hpp
  rychkov.mihail/S1/list/access.hpp
  rychkov.mihail/S1/list/bidirectional_iterator.hpp
  rychkov.mihail/S1/list/construct_destruct.hpp
  rychkov.mihail/S1/list/declaration.hpp
  rychkov.mihail/S1/list/erasors_splice.hpp
  rychkov.mihail/S1/list/inserters.hpp
  rychkov.mihail/S1/list/rest.hpp
  rychkov.mihail/S1/list/sort_based.hpp
  rychkov.mihail/S1/main.cpp
  rychkov.mihail/S1/test-S1-unit.cpp
  rychkov.mihail/S1/test-construct.cpp
  rychkov.mihail/S1/test-erasors.cpp
  rychkov.mihail/S1/test-inserters.cpp
  rychkov.mihail/S1/test-rest.cpp
  rychkov.mihail/S1/test-sort-based.cpp
  rychkov.mihail/S1/test_utils.hpp
  rychkov.mihail/common/functional.hpp
Labels: fine, gr 1, 9/9

#52 kizhin.evgeniy/S1
  kizhin.evgeniy/S1/io-utils.cpp
  kizhin.evgeniy/S1/io-utils.hpp
  kizhin.evgeniy/S1/list-utils.cpp
  kizhin.evgeniy/S1/list-utils.hpp
  kizhin.evgeniy/S1/main.cpp
  kizhin.evgeniy/S1/test-forward-list.cpp
  kizhin.evgeniy/S1/test-module-S1.cpp
  kizhin.evgeniy/S1/test-utils.cpp
  kizhin.evgeniy/S1/test-utils.hpp
  kizhin.evgeniy/S1/type-utils.hpp
  kizhin.evgeniy/common/algorithm-utils.hpp
  kizhin.evgeniy/common/enable-if-input-iterator.hpp
  kizhin.evgeniy/common/forward-list-comparison.hpp
  kizhin.evgeniy/common/forward-list-fwd.hpp
  kizhin.evgeniy/common/forward-list-iterator.hpp
  kizhin.evgeniy/common/forward-list-node.hpp
  kizhin.evgeniy/common/forward-list-swap.hpp
  kizhin.evgeniy/common/forward-list.hpp
Labels: fine, gr 5, 9/9

#56 mozhegova.maria/S1
  mozhegova.maria/S1/constIterator.hpp
  mozhegova.maria/S1/iterator.hpp
  mozhegova.maria/S1/list.hpp
  mozhegova.maria/S1/main.cpp
  mozhegova.maria/S1/node.hpp
  mozhegova.maria/S1/test-list.cpp
  mozhegova.maria/S1/test-main.cpp
Labels: fine, gr 1, 7/9

#65 maslov.aleksey/S1
  maslov.aleksey/S1/iterator.hpp
  maslov.aleksey/S1/list.hpp
  maslov.aleksey/S1/listUtils.cpp
  maslov.aleksey/S1/listUtils.hpp
  maslov.aleksey/S1/main.cpp
  maslov.aleksey/S1/node.hpp
  maslov.aleksey/S1/test-list.cpp
  maslov.aleksey/S1/test-main.cpp
Labels: fine, gr 1, 8/9

#47 kiselev.sergey/S1
  kiselev.sergey/S1/actionsList.cpp
  kiselev.sergey/S1/actionsList.hpp
  kiselev.sergey/S1/iterator.hpp
  kiselev.sergey/S1/list.hpp
  kiselev.sergey/S1/main.cpp
  kiselev.sergey/S1/node.hpp
  kiselev.sergey/S1/test-list.cpp
  kiselev.sergey/S1/test-main.cpp
Labels: fine, gr 5, 8/9
