Repository Volgarenok/spbspu-labs-2025-aads-a, pull requests merged in 2025-06, with the labels that each got.

#54 finaev.alexey/S1
  finaev.alexey/S1/actionsWithList.cpp
  finaev.alexey/S1/actionsWithList.hpp
  finaev.alexey/S1/constIterator.hpp
  finaev.alexey/S1/iterator.hpp
  finaev.alexey/S1/list.hpp
  finaev.alexey/S1/main.cpp
  finaev.alexey/S1/node.hpp
  finaev.alexey/S1/test-list.cpp
  finaev.alexey/S1/test-main.cpp
Labels: fine, gr 1, 5/9

#89 duhanina.alina/S2
  duhanina.alina/S2/main.cpp
  duhanina.alina/S2/test-array.cpp
  duhanina.alina/S2/test-main.cpp
  duhanina.alina/common/array.hpp
  duhanina.alina/common/queue.hpp
  duhanina.alina/common/stack.hpp
Labels: fine, gr 5, 7/9

#128 kiselev.sergey/S5
  kiselev.sergey/S5/keySum.hpp
  kiselev.sergey/S5/main.cpp
  kiselev.sergey/S5/test-main.cpp
  kiselev.sergey/S5/test-traverse.cpp
  kiselev.sergey/common/breadthIterator.hpp
  kiselev.sergey/common/dynamicArr.hpp
  kiselev.sergey/common/lnrIterator.hpp
  kiselev.sergey/common/rnlIterator.hpp
  kiselev.sergey/common/tree.hpp
Labels: fine, gr 5, 8/9

#112 savintsev.ilya/S4
  savintsev.ilya/S4/dataset.cpp
  savintsev.ilya/S4/dataset.h
  savintsev.ilya/S4/main.cpp
  savintsev.ilya/S4/test-default.cpp
  savintsev.ilya/S4/test-ttt.cpp
  savintsev.ilya/S4/two-three-tree.h
  savintsev.ilya/S4/two-three-tree/ttt-body.hpp
  savintsev.ilya/S4/two-three-tree/ttt-const-iterator.hpp
  savintsev.ilya/S4/two-three-tree/ttt-iterator.hpp
  savintsev.ilya/S4/two-three-tree/ttt-node.hpp
Labels: fine, gr 4, 7/9

#61 lanovenko.ivan/S1
  lanovenko.ivan/S1/forward_list.hpp
  lanovenko.ivan/S1/forward_list_const_iterator.hpp
  lanovenko.ivan/S1/forward_list_iterator.hpp
  lanovenko.ivan/S1/forward_list_node.hpp
  lanovenko.ivan/S1/list_manipulations.cpp
  lanovenko.ivan/S1/list_manipulations.hpp
  lanovenko.ivan/S1/main.cpp
  lanovenko.ivan/S1/test-forward_list.cpp
  lanovenko.ivan/S1/test-main.cpp
Labels: fine, gr 1, 5/9

#76 gavrilova.polina/S1
  gavrilova.polina/S1/ConstIteratorFwd.hpp
  gavrilova.polina/S1/FwdList.hpp
  gavrilova.polina/S1/IteratorFwd.hpp
  gavrilova.polina/S1/NodeFwdList.hpp
  gavrilova.polina/S1/inputList.cpp
  gavrilova.polina/S1/inputList.hpp
  gavrilova.polina/S1/main.cpp
  gavrilova.polina/S1/outputList.cpp
  gavrilova.polina/S1/outputList.hpp
  gavrilova.polina/S1/test-FwdList.cpp
  gavrilova.polina/S1/test-main.cpp
Labels: fine, gr 5, trash, comedy artist, 8/9

#79 dribas.sergey/S1
  dribas.sergey/S1/constIterator.hpp
  dribas.sergey/S1/getSequance.cpp
  dribas.sergey/S1/getSequance.hpp
  dribas.sergey/S1/iterator.hpp
  dribas.sergey/S1/list.hpp
  dribas.sergey/S1/main.cpp
  dribas.sergey/S1/node.hpp
  dribas.sergey/S1/outSequance.cpp
  dribas.sergey/S1/outSequance.hpp
  dribas.sergey/S1/test-list.cpp
  dribas.sergey/S1/test-main.cpp
Labels: fine, gr 5, 7/9

#92 zholobov.oleg/S2
  zholobov.oleg/S2/main.cpp
  zholobov.oleg/S2/test-array.cpp
  zholobov.oleg/S2/test-main.cpp
  zholobov.oleg/S2/test-queue.cpp
  zholobov.oleg/S2/test-stack.cpp
  zholobov.oleg/common/array.hpp
  zholobov.oleg/common/queue.hpp
  zholobov.oleg/common/stack.hpp
Labels: fine, gr 5, trash, comedy artist, 7/9

#99 mozhegova.maria/S2
  mozhegova.maria/S2/main.cpp
  mozhegova.maria/S2/queue.hpp
  mozhegova.maria/S2/resize.hpp
  mozhegova.maria/S2/stack.hpp
  mozhegova.maria/S2/test-main.cpp
  mozhegova.maria/S2/test-queue.cpp
  mozhegova.maria/S2/test-stack.cpp
Labels: fine, gr 1, comedy artist, 7/9

#136 tkach.danil/S5
  tkach.danil/S2/main.cpp
  tkach.danil/S2/print.hpp
  tkach.danil/S2/test-queue.cpp
  tkach.danil/S2/test-stack.cpp
  tkach.danil/S4/commands.hpp
  tkach.danil/S4/main.cpp
  tkach.danil/S4/test-tree.cpp
  tkach.danil/S5/key_summ.cpp
  tkach.danil/S5/key_summ.hpp
  tkach.danil/S5/main.cpp
  tkach.danil/S5/test-main.cpp
  tkach.danil/S5/test-traverse.cpp
  tkach.danil/common/AVLtree.hpp
  tkach.danil/common/c_iterator.hpp
  tkach.danil/common/dynamic_array.hpp
  tkach.danil/common/iterator.hpp
  tkach.danil/common/node_tree.hpp
  tkach.danil/common/queue.hpp
  tkach.danil/common/stack.hpp
Labels: fine, gr 1, 6/9

#127 kizhin.evgeniy/S4
  kizhin.evgeniy/S1/type-utils.hpp
  kizhin.evgeniy/S4/command-processor.cpp
  kizhin.evgeniy/S4/command-processor.hpp
  kizhin.evgeniy/S4/dataset.hpp
  kizhin.evgeniy/S4/io-utils.cpp
  kizhin.evgeniy/S4/io-utils.hpp
  kizhin.evgeniy/S4/main.cpp
  kizhin.evgeniy/S4/test-map.cpp
  kizhin.evgeniy/S4/test-module-S4.cpp
  kizhin.evgeniy/S4/test-utils.cpp
  kizhin.evgeniy/S4/test-utils.hpp
  kizhin.evgeniy/common/forward-list-fwd.hpp
  kizhin.evgeniy/common/forward-list-node.hpp
  kizhin.evgeniy/common/forward-list.hpp
  kizhin.evgeniy/common/internal/forward-list-comparison.hpp
  kizhin.evgeniy/common/internal/forward-list-fwd.hpp
  kizhin.evgeniy/common/internal/forward-list-iterator.hpp
  kizhin.evgeniy/common/internal/forward-list-node.hpp
  kizhin.evgeniy/common/internal/forward-list-swap.hpp
  kizhin.evgeniy/common/internal/map-node.hpp
  kizhin.evgeniy/common/map.hpp
  kizhin.evgeniy/common/type-utils.hpp
Labels: fine, gr 5, 9/9

#157 alymova.ksenia/S7
  alymova.ksenia/S7/graph-commands.cpp
  alymova.ksenia/S7/graph-commands.hpp
  alymova.ksenia/S7/graph.cpp
  alymova.ksenia/S7/graph.hpp
  alymova.ksenia/S7/hash-functions.hpp
  alymova.ksenia/S7/hash-iterators.hpp
  alymova.ksenia/S7/hash-node.hpp
  alymova.ksenia/S7/hash-table.hpp
  alymova.ksenia/S7/main.cpp
  alymova.ksenia/S7/test-hash.cpp
  alymova.ksenia/S7/test-main.cpp
  alymova.ksenia/common/list/iterators.hpp
  alymova.ksenia/common/list/list.hpp
Labels: fine, gr 4, 9/9

#155 rychkov.mihail/S5
  rychkov.mihail/S1/main.cpp
  rychkov.mihail/S1/test_utils.hpp
  rychkov.mihail/S2/main.cpp
  rychkov.mihail/S2/test-queue.cpp
  rychkov.mihail/S2/test-stack.cpp
  rychkov.mihail/S2/test-variant.cpp
  rychkov.mihail/S4/main.cpp
  rychkov.mihail/S4/processor.hpp
  rychkov.mihail/S4/test-map.cpp
  rychkov.mihail/S5/main.cpp
  rychkov.mihail/S5/test-S5-unit.cpp
  rychkov.mihail/S5/test-heavy_traverse.cpp
  rychkov.mihail/common/bad_variant_access.cpp
  rychkov.mihail/common/list.hpp
  rychkov.mihail/common/list/access.hpp
  rychkov.mihail/common/list/bidirectional_iterator.hpp
  rychkov.mihail/common/list/construct_destruct.hpp
  rychkov.mihail/common/list/declaration.hpp
  rychkov.mihail/common/list/erasors_splice.hpp
  rychkov.mihail/common/list/inserters.hpp
  rychkov.mihail/common/list/rest.hpp
  rychkov.mihail/common/list/sort_based.hpp
  rychkov.mihail/common/map.hpp
  rychkov.mihail/common/map_base.hpp
  rychkov.mihail/common/map_base/access.hpp
  rychkov.mihail/common/map_base/construct_destruct.hpp
  rychkov.mihail/common/map_base/declaration.hpp
  rychkov.mihail/common/map_base/emplace_impl.hpp
  rychkov.mihail/common/map_base/erase.hpp
  rychkov.mihail/common/map_base/heavy_iterator.hpp
  rychkov.mihail/common/map_base/indexers.hpp
  rychkov.mihail/common/map_base/insert.hpp
  rychkov.mihail/common/map_base/iterator.hpp
  rychkov.mihail/common/map_base/node.hpp
  rychkov.mihail/common/map_base/search.hpp
  rychkov.mihail/common/map_base/traverses.hpp
  rychkov.mihail/common/parser.cpp
  rychkov.mihail/common/parser.hpp
  rychkov.mihail/common/queue.hpp
  rychkov.mihail/common/queue_base.hpp
  rychkov.mihail/common/safe_math.hpp
  rychkov.mihail/common/set.hpp
  rychkov.mihail/common/stack.hpp
  rychkov.mihail/common/variant.hpp
  rychkov.mihail/common/variant/base/copy_move_assign_base.hpp
  rychkov.mihail/common/variant/base/copy_move_construct_base.hpp
  rychkov.mihail/common/variant/base/getters.hpp
  rychkov.mihail/common/variant/base/route_visit.hpp
  rychkov.mihail/common/variant/base/union_base.hpp
  rychkov.mihail/common/variant/base/visitor_helpers.hpp
  rychkov.mihail/common/variant/bases.hpp
  rychkov.mihail/common/variant/class/access.hpp
  rychkov.mihail/common/variant/class/construct_destruct.hpp
  rychkov.mihail/common/variant/class/visit.hpp
  rychkov.mihail/common/variant/declaration.hpp
  rychkov.mihail/common/variant/tools.hpp
  rychkov.mihail/common/variant/traits.hpp
Labels: fine, gr 1, 9/9

#141 savintsev.ilya/S5
  savintsev.ilya/S2/postfix-expression.h
  savintsev.ilya/S2/stack.hpp
  savintsev.ilya/S2/test-dynamic-array.cpp
  savintsev.ilya/S4/dataset.h
  savintsev.ilya/S4/test-ttt.cpp
  savintsev.ilya/S5/cmds.hpp
  savintsev.ilya/S5/main.cpp
  savintsev.ilya/common/dynamic-array.hpp
  savintsev.ilya/common/queue.hpp
  savintsev.ilya/common/two-three-tree.h
  savintsev.ilya/common/two-three-tree/ttt-body.hpp
  savintsev.ilya/common/two-three-tree/ttt-const-iterator.hpp
  savintsev.ilya/common/two-three-tree/ttt-iterator.hpp
  savintsev.ilya/common/two-three-tree/ttt-node.hpp
Labels: fine, gr 4, 6/9

#148 demehin.maxim/S7
  demehin.maxim/S7/commands.cpp
  demehin.maxim/S7/commands.hpp
  demehin.maxim/S7/graph.cpp
  demehin.maxim/S7/graph.hpp
  demehin.maxim/S7/hash_table.hpp
  demehin.maxim/S7/hash_table_iterator.hpp
  demehin.maxim/S7/main.cpp
  demehin.maxim/S7/test-main.cpp
  demehin.maxim/S7/test-table.cpp
  demehin.maxim/common/dynamic_array.hpp
  demehin.maxim/common/dynamic_array_citerator.hpp
  demehin.maxim/common/dynamic_array_iterator.hpp
  demehin.maxim/common/list/list.hpp
  demehin.maxim/common/list/list_iterator.hpp
  demehin.maxim/common/list/list_node.hpp
Labels: fine, 6/9

#145 kizhin.evgeniy/S5
  kizhin.evgeniy/S5/main.cpp
  kizhin.evgeniy/S5/map-utils.cpp
  kizhin.evgeniy/S5/map-utils.hpp
  kizhin.evgeniy/S5/test-iterators.cpp
  kizhin.evgeniy/S5/test-module-S5.cpp
  kizhin.evgeniy/common/map.hpp
Labels: fine, gr 5, 9/9

#107 Bocharov.egor/S2
  bocharov.egor/S2/actions.cpp
  bocharov.egor/S2/actions.hpp
  bocharov.egor/S2/main.cpp
  bocharov.egor/S2/test-array.cpp
  bocharov.egor/S2/test-main.cpp
  bocharov.egor/S2/test-queue.cpp
  bocharov.egor/S2/test-stack.cpp
  bocharov.egor/common/array.hpp
  bocharov.egor/common/queue.hpp
  bocharov.egor/common/stack.hpp
Labels: fine, gr 5, 7/9

#115 duhanina.alina/S4
  duhanina.alina/S2/main.cpp
  duhanina.alina/S4/main.cpp
  duhanina.alina/S4/test-main.cpp
  duhanina.alina/S4/test-tree.cpp
  duhanina.alina/common/array.hpp
  duhanina.alina/common/cIterator.hpp
  duhanina.alina/common/iterator.hpp
  duhanina.alina/common/node.hpp
  duhanina.alina/common/tree.hpp
Labels: fine, gr 5, 6/9

#100 lanovenko.ivan/S2
  lanovenko.ivan/S2/array.hpp
  lanovenko.ivan/S2/conversion_to_postfix.cpp
  lanovenko.ivan/S2/conversion_to_postfix.hpp
  lanovenko.ivan/S2/expression_calculations.cpp
  lanovenko.ivan/S2/expression_calculations.hpp
  lanovenko.ivan/S2/input_output_expressions.cpp
  lanovenko.ivan/S2/input_output_expressions.hpp
  lanovenko.ivan/S2/main.cpp
  lanovenko.ivan/S2/queue.hpp
  lanovenko.ivan/S2/stack.hpp
  lanovenko.ivan/S2/test-main.cpp
  lanovenko.ivan/S2/test-queue.cpp
  lanovenko.ivan/S2/test-stack.cpp
Labels: fine, gr 1, 6/9

#166 rychkov.mihail/S7
  rychkov.mihail/S4/main.cpp
  rychkov.mihail/S4/processor.cpp
  rychkov.mihail/S4/processor.hpp
  rychkov.mihail/S4/test-map.cpp
  rychkov.mihail/S7/main.cpp
  rychkov.mihail/S7/processor.cpp
  rychkov.mihail/S7/processor.hpp
  rychkov.mihail/S7/test-S7-unit.cpp
  rychkov.mihail/S7/test-unordered_map.cpp
  rychkov.mihail/common/map_base/declaration.hpp
  rychkov.mihail/common/map_base/emplace_impl.hpp
  rychkov.mihail/common/map_base/insert.hpp
  rychkov.mihail/common/mem_checker.hpp
  rychkov.mihail/common/parser.cpp
  rychkov.mihail/common/parser.hpp
  rychkov.mihail/common/type_traits.hpp
  rychkov.mihail/common/unordered_base.hpp
  rychkov.mihail/common/unordered_base/access.hpp
  rychkov.mihail/common/unordered_base/construct_destruct.hpp
  rychkov.mihail/common/unordered_base/declaration.hpp
  rychkov.mihail/common/unordered_base/indexers.hpp
  rychkov.mihail/common/unordered_base/iterator.hpp
  rychkov.mihail/common/unordered_base/memory.hpp
  rychkov.mihail/common/unordered_base/modifiers.hpp
  rychkov.mihail/common/unordered_base/search.hpp
  rychkov.mihail/common/unordered_map.hpp
  rychkov.mihail/common/unordered_set.hpp
Labels: fine, gr 1, 9/9

#124 lanovenko.ivan/S4
  lanovenko.ivan/S4/command_processing.cpp
  lanovenko.ivan/S4/command_processing.hpp
  lanovenko.ivan/S4/input_output_dictionaries.cpp
  lanovenko.ivan/S4/input_output_dictionaries.hpp
  lanovenko.ivan/S4/main.cpp
  lanovenko.ivan/S4/test-main.cpp
  lanovenko.ivan/S4/test-tree.cpp
  lanovenko.ivan/common/tree.hpp
  lanovenko.ivan/common/tree_const_iterator.hpp
  lanovenko.ivan/common/tree_iterator.hpp
  lanovenko.ivan/common/tree_node.hpp
Labels: fine, gr 1, 5/9

#151 zholobov.oleg/S4
  zholobov.oleg/S4/main.cpp
  zholobov.oleg/S4/test-main.cpp
  zholobov.oleg/S4/test-tree.cpp
  zholobov.oleg/S4/tree_actions.cpp
  zholobov.oleg/S4/tree_actions.hpp
  zholobov.oleg/common/tree/node.hpp
  zholobov.oleg/common/tree/tree.hpp
  zholobov.oleg/common/tree/tree_iterators.hpp
Labels: fine, 7/9

#152 Brevnov.nikita/s4
  brevnov.nikita/S4/commandList.cpp
  brevnov.nikita/S4/commandList.hpp
  brevnov.nikita/S4/iterator.hpp
  brevnov.nikita/S4/main.cpp
  brevnov.nikita/S4/test-main.cpp
  brevnov.nikita/S4/test-tree.cpp
  brevnov.nikita/S4/tree.hpp
  brevnov.nikita/S4/treeNode.hpp
Labels: fine, gr 5, 7/9

#159 Brevnov.nikita/s5
  brevnov.nikita/S4/tree.hpp
  brevnov.nikita/S5/keySum.cpp
  brevnov.nikita/S5/keySum.hpp
  brevnov.nikita/S5/main.cpp
  brevnov.nikita/S5/test-main.cpp
  brevnov.nikita/S5/test-traverse.cpp
  brevnov.nikita/common/brIterator.hpp
  brevnov.nikita/common/dynamic_array.hpp
  brevnov.nikita/common/iterator.hpp
  brevnov.nikita/common/lnrIterator.hpp
  brevnov.nikita/common/queue.hpp
  brevnov.nikita/common/rnlIterator.hpp
  brevnov.nikita/common/stack.hpp
  brevnov.nikita/common/tree.hpp
  brevnov.nikita/common/treeNode.hpp
Labels: fine, gr 5, 8/9

#162 lanovenko.ivan/S5
  lanovenko.ivan/S5/accumulator.cpp
  lanovenko.ivan/S5/accumulator.hpp
  lanovenko.ivan/S5/main.cpp
Labels: gr 1, 6/9

#181 duhanina.alina/S7
  duhanina.alina/S1/citerator.hpp
  duhanina.alina/S1/iterator.hpp
  duhanina.alina/S1/node.hpp
  duhanina.alina/S7/commands.cpp
  duhanina.alina/S7/commands.hpp
  duhanina.alina/S7/graph.cpp
  duhanina.alina/S7/graph.hpp
  duhanina.alina/S7/main.cpp
  duhanina.alina/S7/test-hashTable.cpp
  duhanina.alina/S7/test-main.cpp
  duhanina.alina/common/HashTable.hpp
  duhanina.alina/common/bucket.hpp
  duhanina.alina/common/iteratorHash.hpp
  duhanina.alina/common/list.hpp
  duhanina.alina/common/listCIterator.hpp
  duhanina.alina/common/listIterator.hpp
  duhanina.alina/common/listNode.hpp
  duhanina.alina/common/prime.cpp
  duhanina.alina/common/prime.hpp
Labels: fine, gr 5, 5/9

#176 maslov.aleksey/S7
  maslov.aleksey/S7/commands.cpp
  maslov.aleksey/S7/commands.hpp
  maslov.aleksey/S7/graph.cpp
  maslov.aleksey/S7/graph.hpp
  maslov.aleksey/S7/hashNode.hpp
  maslov.aleksey/S7/hashTable.hpp
  maslov.aleksey/S7/iterator.hpp
  maslov.aleksey/S7/main.cpp
  maslov.aleksey/S7/test-hashTable.cpp
  maslov.aleksey/S7/test-main.cpp
Labels: fine, gr 1, 6/9

#172 maslevtsov.stanislav/S7
  maslevtsov.stanislav/S1/fwd_list_operations.cpp
  maslevtsov.stanislav/S1/fwd_list_operations.hpp
  maslevtsov.stanislav/S1/main.cpp
  maslevtsov.stanislav/S1/test-fwd_list.cpp
  maslevtsov.stanislav/S7/bind_functor.hpp
  maslevtsov.stanislav/S7/commands.cpp
  maslevtsov.stanislav/S7/commands.hpp
  maslevtsov.stanislav/S7/graph.cpp
  maslevtsov.stanislav/S7/graph.hpp
  maslevtsov.stanislav/S7/main.cpp
  maslevtsov.stanislav/S7/pair_hash.hpp
  maslevtsov.stanislav/S7/test-S7.cpp
  maslevtsov.stanislav/S7/test-hash_table.cpp
  maslevtsov.stanislav/common/fwd_list/declaration.hpp
  maslevtsov.stanislav/common/fwd_list/definition.hpp
  maslevtsov.stanislav/common/fwd_list/fwd_iterator.hpp
  maslevtsov.stanislav/common/fwd_list/fwd_list_node.hpp
  maslevtsov.stanislav/common/hash_table/declaration.hpp
  maslevtsov.stanislav/common/hash_table/definition.hpp
  maslevtsov.stanislav/common/hash_table/hash_table_iterator.hpp
  maslevtsov.stanislav/common/hash_table/slot.hpp
  maslevtsov.stanislav/common/tree/declaration.hpp
  maslevtsov.stanislav/common/tree/tree_iterator.hpp
  maslevtsov.stanislav/common/vector/declaration.hpp
  maslevtsov.stanislav/common/vector/definition.hpp
  maslevtsov.stanislav/common/vector/vector_iterator.hpp
Labels: fine, gr 4, 7/9

#183 kizhin.evgeniy/S7
  kizhin.evgeniy/S7/command-processor.cpp
  kizhin.evgeniy/S7/command-processor.hpp
  kizhin.evgeniy/S7/graph.cpp
  kizhin.evgeniy/S7/graph.hpp
  kizhin.evgeniy/S7/io-utils.cpp
  kizhin.evgeniy/S7/io-utils.hpp
  kizhin.evgeniy/S7/main.cpp
  kizhin.evgeniy/S7/test-module-S7.cpp
  kizhin.evgeniy/S7/test-unordered-map.cpp
  kizhin.evgeniy/common/unordered-map.hpp
Labels: fine, 7/9

#191 mozhegova.maria/S7
  mozhegova.maria/S7/commands.cpp
  mozhegova.maria/S7/commands.hpp
  mozhegova.maria/S7/graph.cpp
  mozhegova.maria/S7/graph.hpp
  mozhegova.maria/S7/main.cpp
  mozhegova.maria/S7/test-hashTable.cpp
  mozhegova.maria/S7/test-main.cpp
  mozhegova.maria/common/dynamicArray.hpp
  mozhegova.maria/common/hashConstIter.hpp
  mozhegova.maria/common/hashIter.hpp
  mozhegova.maria/common/hashSlot.hpp
  mozhegova.maria/common/hashTable.hpp
Labels: fine, gr 1, 6/9

#135 finaev.alexey/S4
  finaev.alexey/S4/commands.cpp
  finaev.alexey/S4/commands.hpp
  finaev.alexey/S4/inputDict.cpp
  finaev.alexey/S4/inputDict.hpp
  finaev.alexey/S4/main.cpp
  finaev.alexey/S4/test-main.cpp
  finaev.alexey/S4/test-tree.cpp
  finaev.alexey/common/AVLtree.hpp
  finaev.alexey/common/constIterator.hpp
  finaev.alexey/common/iterator.hpp
  finaev.alexey/common/treeNode.hpp
Labels: fine, gr 1, 5/9

#104 zakirov.marat/S2
  zakirov.marat/S2/main.cpp
  zakirov.marat/S2/postfix.cpp
  zakirov.marat/S2/postfix.hpp
  zakirov.marat/S2/queue.hpp
  zakirov.marat/S2/stack.hpp
  zakirov.marat/S2/test-main.cpp
  zakirov.marat/S2/test-postfix.cpp
  zakirov.marat/S2/test-queue.cpp
  zakirov.marat/S2/test-stack.cpp
Labels: fine, gr 4, 8/9

#149 dribas.sergey/S4
  dribas.sergey/S4/cmds.cpp
  dribas.sergey/S4/cmds.hpp
  dribas.sergey/S4/main.cpp
  dribas.sergey/S4/test-main.cpp
  dribas.sergey/S4/test-tree.cpp
  dribas.sergey/common/avlTree.hpp
  dribas.sergey/common/constIterator.hpp
  dribas.sergey/common/iterator.hpp
Labels: fine, gr 5, comedy artist, 6/9

#174 Bocharov.egor/S4
  bocharov.egor/S4/main.cpp
  bocharov.egor/S4/test-main.cpp
  bocharov.egor/S4/test-tree.cpp
  bocharov.egor/S4/tree_manips.cpp
  bocharov.egor/S4/tree_manips.hpp
  bocharov.egor/common/cIterator.hpp
  bocharov.egor/common/iterator.hpp
  bocharov.egor/common/node.hpp
  bocharov.egor/common/tree.hpp
Labels: fine, gr 5, trash, 7/9

#133 zakirov.marat/S4
  zakirov.marat/S4/BiIterator.hpp
  zakirov.marat/S4/BiNode.hpp
  zakirov.marat/S4/BiTree.hpp
  zakirov.marat/S4/InputDictionaries.hpp
  zakirov.marat/S4/ProcessingDictionary.hpp
  zakirov.marat/S4/main.cpp
  zakirov.marat/S4/test-BiTree.cpp
  zakirov.marat/S4/test-main.cpp
Labels: fine, gr 4, 7/9

#126 petrov.nikita/S4
  petrov.nikita/S4/avl_tree.hpp
  petrov.nikita/S4/commands.cpp
  petrov.nikita/S4/commands.hpp
  petrov.nikita/S4/main.cpp
  petrov.nikita/S4/test-avl_tree.cpp
  petrov.nikita/S4/test-main.cpp
Labels: fine, gr 1, comedy artist, 5/9

#147 gavrilova.polina/S4
  gavrilova.polina/S4/commands.cpp
  gavrilova.polina/S4/commands.hpp
  gavrilova.polina/S4/main.cpp
  gavrilova.polina/S4/test-TwoThreeTree.cpp
  gavrilova.polina/S4/test-main.cpp
  gavrilova.polina/common/tree/ConstIterator.hpp
  gavrilova.polina/common/tree/Iterator.hpp
  gavrilova.polina/common/tree/NodeTTT.hpp
  gavrilova.polina/common/tree/TwoThreeTree.hpp
Labels: fine, gr 5, comedy artist, 8/9

#205 lanovenko.ivan/S7
  lanovenko.ivan/S7/command_processing.cpp
  lanovenko.ivan/S7/command_processing.hpp
  lanovenko.ivan/S7/graph.cpp
  lanovenko.ivan/S7/graph.hpp
  lanovenko.ivan/S7/hash_table.hpp
  lanovenko.ivan/S7/iterator.hpp
  lanovenko.ivan/S7/main.cpp
  lanovenko.ivan/S7/node.hpp
  lanovenko.ivan/S7/test-hash_table.cpp
  lanovenko.ivan/S7/test-main.cpp
Labels: fine, 6/9

#187 maslov.aleksey/F0
  maslov.aleksey/F0/commands.cpp
  maslov.aleksey/F0/commands.hpp
  maslov.aleksey/F0/main.cpp
  maslov.aleksey/S1/listUtils.hpp
  maslov.aleksey/S1/main.cpp
  maslov.aleksey/S1/test-list.cpp
  maslov.aleksey/S4/commands.hpp
  maslov.aleksey/S4/test-tree.cpp
  maslov.aleksey/S5/main.cpp
  maslov.aleksey/S7/graph.hpp
  maslov.aleksey/S7/test-hashTable.cpp
  maslov.aleksey/common/hashTable/hashNode.hpp
  maslov.aleksey/common/hashTable/hashTable.hpp
  maslov.aleksey/common/hashTable/iterator.hpp
  maslov.aleksey/common/list/iterator.hpp
  maslov.aleksey/common/list/list.hpp
  maslov.aleksey/common/list/node.hpp
  maslov.aleksey/common/tree/iterator.hpp
  maslov.aleksey/common/tree/node.hpp
  maslov.aleksey/common/tree/tree.hpp
Labels: fine, gr 1

#184 tkach.danil/F0
  tkach.danil/F0/commands.cpp
  tkach.danil/F0/commands.hpp
  tkach.danil/F0/main.cpp
  tkach.danil/S1/list_const_iterator.hpp
  tkach.danil/S1/list_iterator.hpp
  tkach.danil/S1/main.cpp
  tkach.danil/S1/test-list.cpp
  tkach.danil/S4/test-tree.cpp
  tkach.danil/common/AVLtree.hpp
  tkach.danil/common/hash_dyn_array.hpp
  tkach.danil/common/list.hpp
  tkach.danil/common/list_const_iterator.hpp
  tkach.danil/common/list_iterator.hpp
  tkach.danil/common/node.hpp
Labels: fine, gr 1

#53 abramov.vladislav/S1
  abramov.vladislav/S1/cIterator.hpp
  abramov.vladislav/S1/input_outputLists.cpp
  abramov.vladislav/S1/input_outputLists.hpp
  abramov.vladislav/S1/iterator.hpp
  abramov.vladislav/S1/list.hpp
  abramov.vladislav/S1/main.cpp
  abramov.vladislav/S1/node.hpp
  abramov.vladislav/S1/outputSums.cpp
  abramov.vladislav/S1/outputSums.hpp
  abramov.vladislav/S1/test-citerator.cpp
  abramov.vladislav/S1/test-iterator.cpp
  abramov.vladislav/S1/test-list.cpp
  abramov.vladislav/S1/test-main.cpp
Labels: fine, gr 4, 7/9

#189 alymova.ksenia/F0
  alymova.ksenia/F0/commands.cpp
  alymova.ksenia/F0/commands.hpp
  alymova.ksenia/F0/dict-input-output.cpp
  alymova.ksenia/F0/dict-input-output.hpp
  alymova.ksenia/F0/main.cpp
  alymova.ksenia/common/list/iterators.hpp
  alymova.ksenia/common/list/list.hpp
  alymova.ksenia/common/tree/tree-2-3.hpp
Labels: fine, gr 4

#192 maslevtsov.stanislav/F0
  maslevtsov.stanislav/F0/bfs_commands.cpp
  maslevtsov.stanislav/F0/bfs_commands.hpp
  maslevtsov.stanislav/F0/graph.cpp
  maslevtsov.stanislav/F0/graph.hpp
  maslevtsov.stanislav/F0/graph_commands.cpp
  maslevtsov.stanislav/F0/graph_commands.hpp
  maslevtsov.stanislav/F0/main.cpp
Labels: fine, gr 4

#194 savintsev.ilya/F0
  savintsev.ilya/F0/confirmation-src.cpp
  savintsev.ilya/F0/confirmation-src.hpp
  savintsev.ilya/F0/file-system.cpp
  savintsev.ilya/F0/file-system.hpp
  savintsev.ilya/F0/main.cpp
  savintsev.ilya/F0/project-body.hpp
  savintsev.ilya/F0/project-cmds.cpp
  savintsev.ilya/F0/project-cmds.hpp
  savintsev.ilya/F0/renderer.hpp
  savintsev.ilya/S1/main.cpp
  savintsev.ilya/S1/test-list.cpp
  savintsev.ilya/common/base-types.cpp
  savintsev.ilya/common/base-types.hpp
  savintsev.ilya/common/complexquad.cpp
  savintsev.ilya/common/complexquad.hpp
  savintsev.ilya/common/concave.cpp
  savintsev.ilya/common/concave.hpp
  savintsev.ilya/common/geometry-utils.cpp
  savintsev.ilya/common/geometry-utils.hpp
  savintsev.ilya/common/io-delimiter.cpp
  savintsev.ilya/common/io-delimiter.hpp
  savintsev.ilya/common/list-iterators.hpp
  savintsev.ilya/common/list-node.hpp
  savintsev.ilya/common/list.hpp
  savintsev.ilya/common/rectangle.cpp
  savintsev.ilya/common/rectangle.hpp
  savintsev.ilya/common/scope-guard.cpp
  savintsev.ilya/common/scope-guard.hpp
  savintsev.ilya/common/shape-utils.cpp
  savintsev.ilya/common/shape-utils.hpp
  savintsev.ilya/common/shape.cpp
  savintsev.ilya/common/shape.hpp
Labels: fine, gr 4

#167 demehin.maxim/F0
  demehin.maxim/F0/commands.cpp
  demehin.maxim/F0/commands.hpp
  demehin.maxim/F0/main.cpp
Labels: fine, gr 5

#196 duhanina.alina/F0
  duhanina.alina/F0/main.cpp
  duhanina.alina/F0/shannonFano.cpp
  duhanina.alina/F0/shannonFano.hpp
  duhanina.alina/F0/wrapper.cpp
  duhanina.alina/F0/wrapper.hpp
Labels: fine, gr 5

#201 kizhin.evgeniy/F0
  kizhin.evgeniy/F0/command-processor.cpp
  kizhin.evgeniy/F0/command-processor.hpp
  kizhin.evgeniy/F0/freq-dict.cpp
  kizhin.evgeniy/F0/freq-dict.hpp
  kizhin.evgeniy/F0/main.cpp
  kizhin.evgeniy/F0/state.cpp
  kizhin.evgeniy/F0/state.hpp
  kizhin.evgeniy/S4/test-map.cpp
  kizhin.evgeniy/common/map.hpp
Labels: fine, gr 5

#193 rychkov.mihail/F0
  rychkov.mihail/F0/boost_link_deps.cpp
  rychkov.mihail/F0/compare.cpp
  rychkov.mihail/F0/compare.hpp
  rychkov.mihail/F0/content.cpp
  rychkov.mihail/F0/content.hpp
  rychkov.mihail/F0/cparser.cpp
  rychkov.mihail/F0/cparser.hpp
  rychkov.mihail/F0/lexer.cpp
  rychkov.mihail/F0/lexer.hpp
  rychkov.mihail/F0/log.cpp
  rychkov.mihail/F0/log.hpp
  rychkov.mihail/F0/main.cpp
  rychkov.mihail/F0/main_processor.cpp
  rychkov.mihail/F0/main_processor.hpp
  rychkov.mihail/F0/main_processor_deependencies.cpp
  rychkov.mihail/F0/main_processor_diff.cpp
  rychkov.mihail/F0/main_processor_info.cpp
  rychkov.mihail/F0/main_processor_init.cpp
  rychkov.mihail/F0/main_processor_load.cpp
  rychkov.mihail/F0/main_processor_save.cpp
  rychkov.mihail/F0/parse_braces.cpp
  rychkov.mihail/F0/parse_folding.cpp
  rychkov.mihail/F0/parse_keywords.cpp
  rychkov.mihail/F0/parse_operator.cpp
  rychkov.mihail/F0/parse_semicolon.cpp
  rychkov.mihail/F0/parse_specials.cpp
  rychkov.mihail/F0/parse_type_calculating.cpp
  rychkov.mihail/F0/preprocessor.cpp
  rychkov.mihail/F0/preprocessor.hpp
  rychkov.mihail/F0/preprocessor_commands.cpp
  rychkov.mihail/F0/preprocessor_stream_parsing.cpp
  rychkov.mihail/F0/print_content.hpp
  rychkov.mihail/F0/print_entities.cpp
  rychkov.mihail/F0/print_expression.cpp
  rychkov.mihail/F0/print_type.cpp
  rychkov.mihail/F0/type_parse_char.cpp
  rychkov.mihail/F0/type_parse_name.cpp
  rychkov.mihail/F0/type_parser.cpp
  rychkov.mihail/F0/type_parser.hpp
  rychkov.mihail/common/algorithm.hpp
  rychkov.mihail/common/map_base/declaration.hpp
  rychkov.mihail/common/map_base/erase.hpp
  rychkov.mihail/common/map_base/insert.hpp
  rychkov.mihail/common/map_base/search.hpp
  rychkov.mihail/common/parser.cpp
  rychkov.mihail/common/variant/base/copy_move_construct_base.hpp
  rychkov.mihail/common/variant/base/union_base.hpp
  rychkov.mihail/common/variant/class/access.hpp
  rychkov.mihail/common/variant/declaration.hpp
Labels: fine, gr 1

#207 Bocharov.egor/S7
  bocharov.egor/S7/commands.cpp
  bocharov.egor/S7/commands.hpp
  bocharov.egor/S7/graph.hpp
  bocharov.egor/S7/hashTable.hpp
  bocharov.egor/S7/iteratorHash.hpp
  bocharov.egor/S7/main.cpp
  bocharov.egor/S7/test-hashTable.cpp
  bocharov.egor/S7/test-main.cpp
Labels: fine, gr 5, comedy artist, 6/9

#209 lanovenko.ivan/F0
  lanovenko.ivan/F0/command_processing.cpp
  lanovenko.ivan/F0/command_processing.hpp
  lanovenko.ivan/F0/input_output_processing.cpp
  lanovenko.ivan/F0/input_output_processing.hpp
  lanovenko.ivan/F0/main.cpp
  lanovenko.ivan/F0/pantsir.cpp
  lanovenko.ivan/F0/pantsir.hpp
  lanovenko.ivan/F0/target.cpp
  lanovenko.ivan/F0/target.hpp
Labels: fine, gr 1

#210 dribas.sergey/F0
  dribas.sergey/F0/commands.cpp
  dribas.sergey/F0/commands.hpp
  dribas.sergey/F0/main.cpp
  dribas.sergey/F0/race_predictor.cpp
  dribas.sergey/F0/race_predictor.hpp
  dribas.sergey/F0/rest_time.cpp
  dribas.sergey/F0/rest_time.hpp
  dribas.sergey/F0/streamGuard.cpp
  dribas.sergey/F0/streamGuard.hpp
  dribas.sergey/F0/survival.cpp
  dribas.sergey/F0/survival.hpp
  dribas.sergey/F0/workout.cpp
  dribas.sergey/F0/workout.hpp
Labels: fine, gr 5, trash, comedy artist
